### ISSUE TITLE
Multiple Vaadin init messages during startup

### ISSUE THREAD

**Issue by Legioth** [vaadin/skeleton-starter-flow#113]
When I start the application with the `master` branch, the console will print four separate messages about running in DEBUG MODE.
```
[qtp1658578510-15] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
[qtp1658578510-15] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
[qtp1658578510-14] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
[qtp1658578510-14] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
===========================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
===========================================================
```

On the `v11` branch, there is only one such message.

**Comment by Legioth** [comment]
Removing the `@PWA` annotation form `MainView` reduces the number of copies to only two instead of four.

**Comment by caalador** [comment]
This came with the change https://github.com/vaadin/flow/pull/4674 after which we now create a DeploymentConfiguration for each ServletRegistration. And each time we create a `DefaultDeploymentConfiguration` we check for production mode and print out the message

**Comment by caalador** [comment]
As a worst case we get 6 warnings for Debug Mode.

2 on `ServletContextListeners` context initialization both from `ServletDeployer` which generates a `DefaultDeploymentConfiguration` for each servletRegistration in the context (always 2)
Then we might add 2 servlets to the `ServletContext` which makes us have 4 servlets.

And then on first open on site we initialize all servlets (2-4) and each of them create their own 
`DefaultDeploymentConfiguration` that log the warning

**Comment by caalador** [comment]
1.3-SNAPSHOT

**Comment by Legioth** [comment]
So the issue in this repo is closed, even though there is no branch in this repo where the fix is actually in use?

**Comment by caalador** [comment]
It's not a skeleton issue. And it is released in Flow 1.2.1 which will flow here at some point.

**Comment by Legioth** [comment]
This issue is filed in this repository, regardless of where the actual fix was made. When the issue in this repository was closed, I assumed that the fix would also be observable through the code in this repository.

**Comment by caalador** [comment]
Right. 
Next time I'll remember to close the ticket after investigation points to another repo and open a new issue there.
