### ISSUE TITLE
Java icon appears in the dock when starting the server

### ISSUE THREAD

**Issue by Legioth** [vaadin/skeleton-starter-flow#114]
When starting the application on OS X, a `java` icon appears in the Dock. This most likely happens because the new PWA features uses AWT for image manipulation, but the headless flag is not set.

Does not happen on the `v11` branch.

**Comment by SomeoneToIgnore** [comment]
Can you elaborate on how do I need to start an app to reproduce the issue?

When I run `mvn jetty:run`, Dock does not change.
I cannot do `java -jar` on the resulting war also due to missing manifest.

**Comment by Legioth** [comment]
It doesn't happen during Jetty startup, but only in association with the first request.

**Comment by Legioth** [comment]
Removing the `@PWA` annotation form `MainView` makes the problem go away.

**Comment by SomeoneToIgnore** [comment]
Indeed, thanks.
