### ISSUE TITLE
Something goes wrong when adding Grid to plain java starter

### ISSUE THREAD

**Issue by alump** [vaadin/skeleton-starter-flow#192]
**Setup:**
- Intelllij IDEA 2019.1
- JDK 12
- Maven 3.6.1 (and IDEA is using it, if I use Maven that IDEA includes there are even more issues)

**Steps to reproduce:**
1. Get plain java starter (RC1) from https://vaadin.com/start/latest/project-base
2. Extract zip and import it into your IDE
3. Run `mvn jetty:run` with your IDE
4. Let application start, and verify it works
5. Stop the jetty:run
5. Add Grid to MainView by adding following lines:
`Grid<String> grid = new Grid<>();
  add(grid);`
6. Restart `mvn jetty:run`
7. Wait app to start and refresh the page

**Expect outcome:**
I see empty grid without columns in MainView with click me button.

**Actual outcome:**
Grid breaks the application on browser with: `Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-grid-templatizer" has already been used with this registry` and lots of 'undefined errors' follow.

Even if I run 'mvn clean install jetty:run' app is still broken same way.

**Comment by alump** [comment]
Actually if I check vaadin-bundle file, it looks like grid might be there, but my browser console is full of lines like:

`client-256ADD15704E8A0FFFFAF81AC444EC99.cache.js:54 Uncaught TypeError: Cannot read property 'setSelectionMode' of undefined`

And these undefined errors are also shown in UI

**Comment by alump** [comment]
Not sure if starter or flow issue. Feel free to move to flow side.

**Comment by caalador** [comment]
This issue is due to having 2 diffferent versions in node_modules that are both trying to register to the dom.

The project worked fine after removing `node_modules` and `package-lock.json`

**Comment by marcushellberg** [comment]
I ran into this too with RC2 while trying to follow the Vaadin CRUD tutorial.

**Comment by alump** [comment]
Another similar issue: https://github.com/vaadin/flow/issues/6029

**Comment by ujoni** [comment]
This issues needs to be validated against `14.0.0.rc5`.

**Comment by caalador** [comment]
This is fixed with the latest version that will be rc6.
If issue still persists after rc6 please re-open and update steps for replication.
