### ISSUE TITLE
JRebel reload goes horribly wrong

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/skeleton-starter-flow#196]
OpenJDK11, Vaadin 14 rc2, JRebel

1. Start app with `jetty:run` & JRebel.
2. App starts
3. Click button, get notification
4. Reload triggers for some reason
5. Server connection dialog is shown
6. Several more dialogs are shown, some with jetty directory listing

<img width="1547" alt="Screen Shot 2019-06-27 at 2 20 47 PM" src="https://user-images.githubusercontent.com/883698/60301861-3b397780-98e7-11e9-84c9-1d33886d5a43.png">

**Comment by mstahv** [comment]
Not sure, but this might be the V13+ issue. Related HotSwapAgent change (which is not a perfect fix either): https://github.com/HotswapProjects/HotswapAgent/commit/ece2b2ac59c925fb886c6569eae38bc80f594ac2

**Comment by vesanieminen** [comment]
I've noticed this as well and found out that a workaround is to first run jetty:run without JRebel and 2nd time with JRebel and then it'll work fine.

**Comment by pleku** [comment]
Apparently also hot reload with Tomcat and JRebel works perfectly fine.

**Comment by pleku** [comment]
Closing this issue as we've recently tested JRebel to work out fine with 14.1.

For more information, here is the documentation about code reload setups https://vaadin.com/docs/v14/flow/workflow/workflow-overview.html
