### ISSUE TITLE
Make Skeleton starter available in vcom

### ISSUE THREAD

**Issue by pleku** [vaadin/skeleton-starter-flow#37]
Need to fork the website and add the Starter there manually. Here is an example on doing the same for Beverage Buddy Starter: https://gitlab.vaadin.com/vaadincom/webpage/commit/6f267171d3883531dc9bd4111c9f6f9f57420ad2

The latest version of the starter should also be tagged with `published` tag to get it visible on the website.

**Comment by denis-anisimov** [comment]
https://gitlab.vaadin.com/denis/webpage/commit/22b32d377e8bbb2362129ba02678daa532ea656b
