### ISSUE TITLE
V14 LTS vaadin app downloaded from starter.vaadin.com can't be compiled

### ISSUE THREAD

**Issue by futaz** [vaadin/skeleton-starter-flow#520]
Hi!

[Yesterday you upgraded](https://github.com/vaadin/skeleton-starter-flow/pull/517) the V14 LTS starter from 14.7.7 to 14.7.8 but the 14.7.8 artifacts are not uploaded to [maven central repository](https://mvnrepository.com/artifact/com.vaadin/vaadin-bom) so I can't build the project.

Please upload 14.7.8 artifacts to maven central or downgrade the starter to 14.7.7.

Thanks!

**Comment by manolo** [comment]
The mvnrepository is not officially supported by maven which doesn't always keep all the artifacts in sync. 
Maven central has the artifacts https://search.maven.org/artifact/com.vaadin/vaadin-bom/14.7.8/pom

**Comment by tarekoraby** [comment]
And 14.7.8 projects downloaded from start.vaadin.com seem to be running fine for me. Could you provide more details on the errors you get?

**Comment by futaz** [comment]
Oh, sorry! I thought that mvnrepository.com is the official central maven repository. @manolo pointed out that it's not the case. If I use central repo instead of mvnrepository.com, the project compiles.

Thank you for your help!
