### ISSUE TITLE
Remove workspace.xml from git & add it to .gitignore

### ISSUE THREAD

**Issue by mvysny** [vaadin/skeleton-starter-flow#560]
Currently Intellij's `.idea/workspace.xml` is committed to git. That has the following disadvantages:
1. anytime I open the project, Intellij changes the file immediately, immediately showing that there are git changes in the project.
2. Performing `git reset --hard` throws away those changes *including any launch configurations I've defined*, which is really annoying.

**Comment by tarekoraby** [comment]
Isn't already ignored: https://github.com/vaadin/skeleton-starter-flow/blob/973abd3c47e33cbc6981a869ffff4c4fca9b1f56/.gitignore#L4?

**Comment by mvysny** [comment]
Unfortunately that's not enough, it needs to be removed from repo: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206370779--gitignore-and-idea-workspace-xml

**Comment by tarekoraby** [comment]
I'm afraid I'm not following. The file should be removed from the git repo if it has been committed first. But the current gitignore settings should prevent one from committing the file in the first place. 

Can you please describe the steps needed to replicate the issue?

**Comment by mvysny** [comment]
Sure thing!

So I start with a clean up-to-date v14 branch (sorry, the v14 branch is probably a vital information which I failed to provide earlier):

```
mavi@mavi-vaadin2 ~/w/v/s/1/skeleton-starter-flow (v14)> git st
On branch v14
Your branch is up to date with 'origin/v14'.

nothing to commit, working tree clean
```
I open the project in intellij and add a launch configuration. I'm adding Tomcat/Local launch configuration, but you can add e.g. Maven jetty:run launch configuration to achieve the same thing. Now when I type `git st` in the console I'm getting:
```
mavi@mavi-vaadin2 ~/w/v/s/1/skeleton-starter-flow (v14)> git st
On branch v14
Your branch is up to date with 'origin/v14'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .idea/workspace.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

If I revert the file via `git reset --hard` and re-launch Intellij, the launch configuration is gone.

I just noticed that last commit in the v14 branch added the file; the ticket #552 is related.

**Comment by tarekoraby** [comment]
Got it. But as far as I can tell, there is no fix for this. Either we add `workspace.xml` to the repo, or we risk that many people will be running `npm install` from the IDE prompt (thereby causing the build to potentially fail with mysterious errors).

**Comment by mcollovati** [comment]
Tracking of local changes to the workspace.xml file after cloning the repo can be prevented with the `git update-index --assume-unchanged .idea/workspace.xml` command.
And to revert the setting: `git update-index --no-assume-unchanged .idea/workspace.xml`

This could be a workaround we can add to the README of the project. Not the best solution, but it may help in this situation.
