### ISSUE TITLE
Production mode compilation shows warnings and errors

### ISSUE THREAD

**Issue by mstahv** [vaadin/skeleton-starter-flow#93]
Some warnings:

```
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/mstahv/Downloads/my-starter-project-6/target/frontend/bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html'
[WARNING] The translated URL 'theme/lumo/example-template.html' has no corresponding file on the filesystem, the file is addressed by path='/Users/mstahv/Downloads/my-starter-project-6/target/frontend/theme/lumo/example-template.html'
[INFO] Installing re
```

And error:
```
[ERROR] warning "polymer-build > polymer-project-config@3.13.0" has incorrect peer dependency "polymer-analyzer@^3.0.0-pre.17 || ^3.0.0".
```

**Comment by rmuller** [comment]
Another one:

`(node:30272) Warning: N-API is an experimental feature and could change at any time.` (2 times)

Also some warnings about invalid cookies:

````
WARNING: Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Sun, 06 Jan 2019 20:49:14 -0000". Invalid 'expires' attribute: Sun, 06 Jan 2019 20:49:14 -0000
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Thu, 06 Jan 2039 19:49:14 -0000; secure; HttpOnly". Invalid 'expires' attribute: Thu, 06 Jan 2039 19:49:14 -0000

````

**Comment by ellaouzi** [comment]
[ERROR] (node:18528) Warning: N-API is an experimental feature and could change at any time.

Any Solution?

**Comment by kolle1986** [comment]
Vaadin starter project throws this errors on  mvn clean package -Pproduction-mode 

[ERROR] warning "polymer-build > polymer-project-config@3.13.0" has incorrect peer dependency "polymer-analyzer@^3.0.0-pre.17 || ^3.0.0".

[ERROR] (node:4113) Warning: N-API is an experimental feature and could change at any time.

[ERROR] (node:4117) Warning: N-API is an experimental feature and could change at any time.

Any progress with this?

**Comment by silvan-lincan** [comment]
With Vaadin 13.0.6, in the "vaadin.productionMode" maven profile, I increased the versions for node and yarn and the errors and warnings were reduced to only two:
```
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html' has no corresponding file on the filesystem ...
[ERROR] warning "polymer-build > polymer-project-config@3.13.0" has incorrect peer dependency "polymer-analyzer@^3.0.0-pre.17 || ^3.0.0".
```

```
<configuration>
    <nodeVersion>v8.16.0</nodeVersion>
    <yarnVersion>v1.14.0</yarnVersion>
</configuration>
```

**Comment by mshabarov** [comment]
Cannot get the above errors and warnings with latest Vaadin 24.1, 23.3 and 14.10 versions.
I got several npm packages "deprecated" warnings, but this seems to be another issue.
